version: '3'
services:
  api-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - src-service

  src-service:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    command: python3 main.py
