version: '3'
services:
  regression-task-project:
    build:
      context: ./
      dockerfile: src/Dockerfile
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    command: python3 main.py